export const Colors = {
  warning: "#c43737ff",
  light: {
    background: "#FEFADF",
    primary: "#5F6C37",
    secondary: "#C06313",
    navBackground: "#6a513aff",
    navLabelInactive: "#edededb3",
    createModal: "#B7987B",
    text: "#EDEDED",
    textInactive: "#edededb3",
    textSecondary: "#222222",
    header: "#1a1a1a",
    passwordChecklist: "#acba84",
    searchBar: "#f9f9f9",
  },
  dark: {
    background: "#DCA15D",
    primary: "#273617",
    secondary: "#7A1010",
    navBackground: "#4E2D0E",
    navLabelInactive: "#ededed",
    createModal: "#FEFADF",
    text: "#EDEDED",
    textInactive: "#ededed",
    textSecondary: "#222222",
    header: "#333333",
    passwordChecklist: "#273617",
    searchBar: "#f9f9f9",
  },
};
